apiVersion: apps/v1
kind: Deployment
metadata:
  name: boek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boek
  template:
    metadata:
      labels:
        app: boek
    spec:
      containers:
      - image: okteto.dev/book:latest
        name: boek
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "c8df609b-8795-4821-9454-af66b7c4841a"
        - name: Vless_Path
          value: "/c8df609b-8795-4821-9454-af66b7c4841a"
        - name: Vmess_UUID
          value: "7a050060-ad04-45b4-8ad6-b354d0c0e3b2"
        - name: Vmess_Path
          value: "7a050060-ad04-45b4-8ad6-b354d0c0e3b2"
        - name: Share_Path
          value: "$Share_Path"
